services: docker
env:
  - CONT=xenial
  - CONT=bionic
before_install:
- docker build -t elmertest/$CONT -f ci/Dockerfile-$CONT .
- docker ps -a
script:
- docker build -t elmerfem-build/$CONT -f ci/Dockerfile-elmer-$CONT .
- docker run elmerfem-build/$CONT /bin/sh -c 'CTEST_OUTPUT_ON_FAILURE=1 ctest -LE slow'
notifications:
  email: change
  flowdock:
    secure: "lu9jDOsW8lSOJr/d/7VGxU9nG1AAhc4kPKgfiOnLsBp2CJXVPAmbyaFMmaMfdJdHgM7pGW6fnoJSBtwyYfsB/GmXtmX9vKGwiKfAAGeUIGS15wzllHKjRQm3hDQ/MnO5wmj6r7dcSPjfLhy5ZFuiihoOSsBd9LpcMOetEsg99tA="
